apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app-dev # We'll deploy this app into a specific namespace

bases:
- ../../base # Points to the base configuration

# Using strategic merge patch for simplicity here
patchesStrategicMerge:
- deployment-replicas.yaml

# You could also add common labels or annotations for this overlay
# commonLabels:
#   environment: dev
