apiVersion: v1
kind: Service
metadata:
  name: my-sample-app-service
spec:
  selector:
    app: my-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort # Or LoadBalancer if your K8s on AWS is configured for it
